version: '3.8'

services:
  backend:
    image: python:3.9-slim
    container_name: github-follow-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    image: python:3.9-slim
    container_name: github-follow-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: python -m http.server 3000
    restart: unless-stopped
    depends_on:
      - backend
