# Render部署配置

# render.yaml
services:
  - type: web
    name: github-follow-tool
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /
    autoDeploy: true
