services:
  # Backend API service (FastAPI) - Python environment, not Docker
  - type: web
    name: github-follow-backend
    env: python
    plan: free
    buildCommand: |
      python3 -m pip install --upgrade pip setuptools wheel
      # Install core deps with wheels only to avoid building from source
      pip install --only-binary=:all: \
        fastapi==0.104.1 \
        uvicorn==0.24.0.post1 \
        pydantic==2.5.0 \
        requests==2.31.0 \
        python-multipart==0.0.6 \
        starlette==0.27.0 \
        anyio==4.0.0 \
        h11==0.14.0 \
        sniffio==1.3.0 \
        idna==3.4
      # Fallback to requirements for future edits (will no-op if already satisfied)
      pip install -r backend/requirements.txt
    startCommand: python3 -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    dockerfilePath: ""  # 明确指定不使用Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: RENDER_ENV
        value: python

  # Frontend static site service
  - type: static
    name: github-follow-frontend
    staticPublishPath: frontend/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
