services:
  # Backend API service (FastAPI) - Python environment, not Docker
  - type: web
    name: github-follow-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python3 -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    dockerfilePath: ""  # 明确指定不使用Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: RENDER_ENV
        value: python

  # Frontend static site service
  - type: static
    name: github-follow-frontend
    staticPublishPath: frontend/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
