# Cloudflare Pages部署配置

# wrangler.toml
name = "github-follow-tool"
compatibility_date = "2024-01-01"

[env.production]
name = "github-follow-tool"

[[env.production.services]]
binding = "DOCKER_SERVICE"
service = "github-follow-tool"
environment = "production"

[env.production.vars]
DEBUG = "false"
LOG_LEVEL = "INFO"
